# ML : Regression Multiple

In [1]:
#Importation des packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
#Importation du jeu de données
df = pd.read_csv(r"C:/Users/maserati/Downloads/homeprices_1.csv")
df.head(5)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
#Imputation des valeurs manquantes
median_bedrooms = df.bedrooms.median()
df["bedrooms"] = df["bedrooms"].fillna(median_bedrooms)
df.head(5)


area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
# Modèle
reg = linear_model.LinearRegression()
reg.fit(df[["area","bedrooms","age"]], df["price"])

LinearRegression()

In [5]:
#Vecteur des coefficients
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [6]:
# Constante
reg.intercept_

221323.00186540384

In [8]:
# Prédiction 1 
reg.predict([[3000,3,40]])

C:\Users\maserati\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [9]:
# Prédiction 2
reg.predict([[2500,4,5]])

C:\Users\maserati\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

# Exercice

In [59]:
df1 = pd.read_csv(r"C:/Users/maserati/Downloads/hiring.csv")
df1.sample(5)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
3        two                   10.0                          10      65000
0        NaN                    8.0                           9      50000
2       five                    6.0                           7      60000
4      seven                    9.0                           6      70000
6        ten                    NaN                           7      72000

In [60]:
import math
test_median = math.floor(df1["test_score(out of 10)"].median())
test_median

8

In [61]:
df1["test_score(out of 10)"] = df1["test_score(out of 10)"].fillna(test_median)
df1["experience"] = df1["experience"].fillna("zero")
df1.sample(5)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
7     eleven                    7.0                           8      80000
5      three                    7.0                          10      62000
0       zero                    8.0                           9      50000
6        ten                    8.0                           7      72000
3        two                   10.0                          10      65000

In [62]:
#!pip install word2number
from word2number import w2n

In [63]:
#fonction de conversion
def convert_numb(i):
    return i.apply(w2n.word_to_num)

In [64]:
# Convertir les chiffre en nombre
df1["experience"] = convert_numb(df1["experience"])

In [65]:
df1.sample(5)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
3           2                   10.0                          10      65000
0           0                    8.0                           9      50000
4           7                    9.0                           6      70000
6          10                    8.0                           7      72000
2           5                    6.0                           7      60000

In [66]:
#Modele de regression
reg1 = linear_model.LinearRegression()
reg1.fit(df1[["experience","test_score(out of 10)","interview_score(out of 10)"]], df1["salary($)"])

LinearRegression()

In [67]:
#Coefficient
reg1.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [68]:
# Constante
reg1.intercept_

17737.263464337688

In [69]:
#Prediction 1
reg1.predict([[2,9,6]])

C:\Users\maserati\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [70]:
#Prediction 2
reg1.predict([[12,10,10]])

C:\Users\maserati\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])